SIM ?= icarus

TOPLEVEL_LANG = verilog

VERILOG_SOURCES += $(PWD)/../../hardware/UART/uart_tx.v

COCOTB_TOPLEVEL = uart_tx

COCOTB_TEST_MODULES = test

include $(shell cocotb-config --makefiles)/Makefile.sim